#!/bin/bash
# Created by Sankar Menon
# Change the solver name for running differnt solvers
# Jan 16 2016
# Version - OpenFoam 2.3.x 
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -f 0/alpha.water
cp 0/alpha.water.org 0/alpha.water
runApplication blockMesh
runApplication setFields
#runApplication sclsVOFFoam 
